---
title: "Analyse factorielle des correspondances des causes de décès par pays"
author: "Mkrtchyan, Toure"
format:
  revealjs:
    theme: beige
    slide-level: 1
  pdf: default
editor: visual
---

# Introduction

En 2019, en Afrique subsaharienne, les maladies non transmissibles représentent environ 35 à 40 % des décès chez les adultes, d’après les données mondiales de l’OMS. Intuitivement, les infections pourraient pourtant être considérées comme dominantes, compte tenu du niveau de développement des pays. Cela soulève plusieurs questions centrales pour l’analyse : Existe-t-il un lien entre le niveau de développement des pays et différentes causes de décès ? Quels pays présentent des profils similaires de mortalité ? Afin d’y répondre rigoureusement, il est pertinent de réaliser une Analyse Factorielle des Correspondances (AFC) sur les données enregistrées.

# Analyse factorielle des correspondances des causes de décès par pays

Cette étude vise à analyser les structures de mortalité à l’échelle mondiale en comparant les profils de décès des différents pays. L’AFC permet de représenter simultanément les pays et les causes de décès dans un espace de faible dimension, afin de mettre en évidence des proximités et des oppositions entre profils de mortalité.

# Préparation des données

URL du jeu de données :\
https://www.kaggle.com/datasets/iamsouravbanerjee/cause-of-deaths-around-the-world

Pour cette analyse, nous avons utilisé un jeu de données disponible sur Kaggle, portant sur les causes de mortalité dans le monde. Le jeu de données original couvre la période 1990 à 2019 et recense les effectifs de décès pour 204 pays et territoires, organisés sous la forme d’un tableau pays × causes de décès.
# Analyse exploratoire


on essaie

## Chargement des données

# Visualisation des données par barplots

### Arménie : ouyuiy

